# netlify.toml (place at the root of your authApp repo)

[build]
  command = "npm run build"
  publish = "dist"

# 1) Serve your built assets directly
[[redirects]]
  from   = "/assets/*"
  to     = "/assets/:splat"
  status = 200

# 2) SPA fallback for all other routes
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

# 3) CORS headers for your federated entry
[[headers]]
  for = "/assets/remoteEntry.js"       # or "/remoteEntry.js" if you moved it to dist root
  [headers.values]
    # only allow your host’s origin
    Access-Control-Allow-Origin = "https://chatsyn.netlify.app"
    Access-Control-Allow-Methods = "GET"
    Access-Control-Allow-Credentials = "true"
